name = "Magicrinth"
author = "Sephiroth1993"
version = "0.99B"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a9a87debd46e065da5eb116bee06973304a59c517ccc447797416bb9b29c311b"

[versions]
fabric = "0.17.3"
minecraft = "1.20.1"
